In [ ]:
import csv
from numpy import loadtxt
import pandas as pd

filename = '../data/pima-indians-diabetes.csv'
raw_data = open(filename, 'rb')
# cargar datos #1 convertir datos para operaciones matematicas
data = loadtxt(raw_data, delimiter=',')
print(data.shape)
print(data)




(768, 9)
[[  6. 148.  72. ... 627.  50.   1.]
 [  1.  85.  66. ... 351.  31.   0.]
 [  8. 183.  64. ... 672.  32.   1.]
 ...
 [  5. 121.  72. ... 245.  30.   0.]
 [  1. 126.  60. ... 349.  47.   1.]
 [  1.  93.  70. ... 315.  23.   0.]]


In [ ]:
# forma de agregar contenido con pandas 
import pandas as pd

filename = '../data/pima-indians-diabetes.csv'
name = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = pd.read_csv(filename, names=name)
print(data.shape)
print(data)


# NOMBRE -> pima indians diabetes
# TIPO -> Clasificacion Binaria
# DIMENSIONES -> 768 filas y 9 columnas
# ENTRADAS = (preg) = numericas, press = numericas, skin = numericas, test = numericas, mass = flotante, pedi = flotante, age = numericas, class = numericas (0 o 1,  aunque puede ser booleano) 
# RESULTADO = Nominal porque hay datos que pueden orden especifico -> 2 clases binarios 0 o 1 (0 = no diabetes, 1 = diabetes)

(768, 9)
     preg  plas  pres  skin  test  mass     pedi  age  class
0       6   148    72    35     0  33.6   627.00   50      1
1       1    85    66    29     0  26.6   351.00   31      0
2       8   183    64     0     0  23.3   672.00   32      1
3       1    89    66    23    94  28.1   167.00   21      0
4       0   137    40    35   168  43.1  2288.00   33      1
..    ...   ...   ...   ...   ...   ...      ...  ...    ...
763    10   101    76    48   180  32.9   171.00   63      0
764     2   122    70    27     0  36.8     0.34   27      0
765     5   121    72    23   112  26.2   245.00   30      0
766     1   126    60     0     0  30.1   349.00   47      1
767     1    93    70    31     0  30.4   315.00   23      0

[768 rows x 9 columns]
